cmake_minimum_required(VERSION 3.16)

project(HW3_M11415015 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

find_package(OpenCV REQUIRED)

add_executable(HW3_M11415015 HW3_M11415015.cpp)
target_link_libraries(HW3_M11415015 PRIVATE ${OpenCV_LIBS})
